apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dummy-service-dr
  namespace: mesh-dashboard
spec:
  host: dummy-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dummy-service-vs
  namespace: mesh-dashboard
spec:
  hosts:
    - dummy-service
  http:
    - route:
        - destination:
            host: dummy-service
            subset: v1
          weight: 100
        - destination:
            host: dummy-service
            subset: v2
          weight: 0
